prima_app/urls.py
from django.urls import path
from prima_app.views import homepage,welcome,lista,chi_siamo,variabili,index_prima_app

app_name="prima_app"
urlpatterns=[
    path('homepage',homepage,name='homepage'),
    path('welcome',welcome,name='welcome'),
    path('lista',lista,name='lista'),
    path('chi_siamo',chi_siamo,name='chi_siamo'),
    path('variabili',variabili,name='variabili'),
    path('index_prima_app',index_prima_app,name='index_prima_app'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index_generale

urlpatterns = [

    path('admin/', admin.site.urls),
    path('prima_app/', include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/', include("seconda_app.urls",namespace="seconda_app")),
    path('prova_pratica_0/',include("prova_pratica_0.urls",namespace="prova_pratica_0")),
    path('prova_pratica_2/',include("prova_pratica_2.urls",namespace="prova_pratica_2")),
    path('', index_generale, name="index_generale"),
]

prova_pratica_0/urls.py
from django.urls import path
from prova_pratica_0.views import index_prova,somma,media

app_name="prova_pratica_0"
urlpatterns=[
    path('somma',somma,name='somma'),
    path('media',media,name='media'),
    path('index_prova',index_prova,name='index_prova'),
]

prova_pratica_2/urls.py
from django.urls import path
from  prova_pratica_2.views import view_a,view_b,view_c,index_prova_2
app_name="prova_pratica_2"
urlpatterns=[
    path('view_a',view_a,name='view_a'),
    path('view_b',view_b,name='view_b'),
    path('view_c',view_c,name='view_c'),
    path('index_prova_2',index_prova_2,name='index_prova_2'),
]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import index_seconda_app,es_if,else_if_elif,es_for
app_name="seconda_app"
urlpatterns=[
    path('index_seconda_app',index_seconda_app,name='index_seconda_app'),
    path('es_if',es_if,name='es_if'),
    path('else_if_elif',else_if_elif,name='else_if_elif'),
    path('es_for',es_for,name='es_for'),
]

news/models.py
from django.db import models

# Create your models here.
class Giornalista(models.Model):
    nome=models.CharField(max_length=20)
    cognome=models.CharField(max_length=20)

    def __str__(self):
        return self.nome+" "+self.cognome


        
class Articolo(models.Model):
    """Il modello generico di un articolo di news"""
    titolo= models.CharField(max_length=100)#alcuni campi necessitano di campi obbligatori
    contenuto=models.TextField()
    giornalista = models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")

    def __str__(self):
      return self.titolo  

prova_pratica_2/models.py
from django.db import models

# Create your models here.

news/views.py
from django.shortcuts import render

# Create your views here.

prima_app/views.py
from importlib.resources import contents
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request,"homepage.html")
def welcome(request):
    return render(request,"welcome.html")
def lista(request):
    return render(request,"lista.html")
def chi_siamo(request):
    return render(request,"chi_siamo.html")
def variabili(request):
    context={
        'var1': 'Prima varibile',
        'var2': 'Seconda varibile',
        'var3': 'Terza varibile'
    }
    return render(request,"variabili.html",context)
def index_prima_app(request):
    return render(request,"index_prima_app.html")

primo_progetto/views.py
from django.shortcuts import render
def index_generale(request):
    return render(request,"index_generale.html")

prova_pratica_0/views.py
from importlib.resources import contents
from multiprocessing import context
from re import S, X
from django.shortcuts import render
import random


# Create your views here.
def somma(request):
    x=random.randint(1,10)
    y=random.randint(1,10)
    context={ 
        'var1':x,
        'var2':y,
        'somma': x+y,
    }
    return render(request,"somma.html",context)
def media(request):
    lista=[]
    s=0
    for i in range(30):
        num=random.randint(0,10)
        s+=num
        lista.append(num)
        media=s/30
        context={
            'lista':lista,
            'media':media
        }
    return render(request,"media.html",context)
def index_prova(request):
    return render(request,"index_prova.html")

prova_pratica_2/views.py
from django.shortcuts import render

def view_a(request):
    materie = ["Matematica","Italiano","Inglese","Storia","Geografia"]
    context={
             'materie':materie,
        }
    return render(request,"views_a.html",context)
def view_b(request):
    voti = {'Giuseppe Gullo':[("Matematica",9,0),("Italiano",7,3),("Inglese",7,4),("Storia",7,4),("Geografia",5,7)],
           'Antonio Barbera':[("Matematica",8,1),("Italiano",6,1),("Inglese",9,0),("Storia",8,2),("Geografia",8,1)],
           'Nicola Spina':[("Matematica",7,2),("Italiano",6,2),("Inglese",4,3),("Storia",8,2),("Geografia",8,2)]}
    
    context={
        'voti':voti
     }
    return render(request,"views_b.html",context)
def view_c(request):
    voti = {'Giuseppe Gullo':[("Matematica",9,0),("Italiano",7,3),("Inglese",7,4),("Storia",7,4),("Geografia",5,7)],
           'Antonio Barbera':[("Matematica",8,1),("Italiano",6,1),("Inglese",9,0),("Storia",8,2),("Geografia",8,1)],
           'Nicola Spina':[("Matematica",7,2),("Italiano",6,2),("Inglese",4,3),("Storia",8,2),("Geografia",8,2)]}
    medie = {}
    cont=0
    for key,value in voti.items():
        media=0     
        cont+=1
        print(cont)
        for voto in value:
            media+=voto[1]
        media = media/len(value)
        medie[key]=media
    context={
            'medie':medie,
        }
    return render(request,"views_c.html",context)
def index_prova_2(request):
    return render(request,"index_prova_2.html")

seconda_app/views.py
import datetime
from django.shortcuts import render
def index_seconda_app(request):
    return render(request,"index_seconda_app.html")
def es_if(request):
    context={
        'var1':200,
        'var2':200,
        'var3':300,
    }

    return render(request,"es_if.html",context)
def else_if_elif(request):
    context={
        'var1':100,
        'var2':100.0,
        'var3':100.50,
    }

    return render(request,"else_if_elif.html",context)
def es_for(request):
    context={
       'list1':[1, datetime.date(2019,7,16),'Do not give up'],
       'list2':[1, datetime.date(2019,7,16),'Do not give up']
    }

    return render(request,"es_for.html",context)

prima_app/templates/chi_siamo.html
 {%extends "base.html"%}
        {%block content%}
            <h1>Chi siamo</h1>
            <p>Lorem ipsum</p>
        {%endblock content%}
 

prima_app/templates/homepage.html
{%extends "base.html"%}
    {%block content%}
     <h1>Salve e ben arrivato</h1>
    {%endblock content%}

prima_app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%extends base.html%}
    <title>{%block title %}{{blok.super}}|Index{% endblock title %}</title>
</head>
<body>
    <div class="container my-4">
        {%block content%}
         <ol>
            <li><a href="{% url 'prima_app:homepage'%}">Home page Salve</a></li> 
            <li><a href="{% url 'prima_app:welcome'%}">Welcome</a></li>
            <li><a href="{% url 'prima_app:lista'%}">Lista</a></li>
            <li><a href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a></li>
            <li><a href="{% url 'prima_app:variabili'%}">Variabili</a></li>        
        </ol> 
        {%endblock content%}
      </div>
    
</body>
</html>

prima_app/templates/index_prima_app.html
{%extends "base.html"%}
        {%block content%}
         <ol>
            <li><a href="{% url 'prima_app:homepage'%}">Home page Salve</a></li> 
            <li><a href="{% url 'prima_app:welcome'%}">Welcome</a></li>
            <li><a href="{% url 'prima_app:lista'%}">Lista</a></li>
            <li><a href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a></li>
            <li><a href="{% url 'prima_app:variabili'%}">Variabili</a></li>        
        </ol> 
        {%endblock content%}

prima_app/templates/lista.html
    {%extends "base.html"%}
        {%block content%}
         <ol>
            <li>Primo</li>
            <li>Secondo</li>
            <li>Terzo</li>
        </ol>
        {%endblock content%}

prima_app/templates/variabili.html
    {%extends "base.html"%}
    <title>{%block title %}{{blok.super}}|Variavili{% endblock title %}</title>
        {%block content%}
        <ol>
            <li>{{var1}}</li>
            <li>{{var2}}</li>
            <li>{{var3}}</li>
        </ol>
        {%endblock content%}

prima_app/templates/welcome.html
    {%extends "base.html"%}
        {%block content%}
         <h1>Welcome</h1>
        {%endblock content%}

primo_progetto/templates/index_generale.html
{%extends "base.html"%}
        {%block content%}
    <ol>
        <li><a href="/admin">Admin</a></li>
        <li><a href="{% url 'prima_app:index_prima_app'%}">Prima_App</a></li>
        <li><a href="{% url 'seconda_app:index_seconda_app'%}">Seconda_App</a></li>
        <li><a href="{% url 'prova_pratica_0:index_prova'%}">Prova_pratica_0</a></li>
        <li><a href="{% url 'prova_pratica_2:index_prova_2'%}">Prova_pratica_2</a></li>
        
    </ol>
    {%endblock content%}

prova_pratica_0/templates/index_prova.html
{%extends "base.html"%}
     {%block content%}
         <ol>
            <li><a href="{% url 'prova_pratica_0:somma'%}">Somma</a></li> 
            <li><a href="{% url 'prova_pratica_0:media'%}">Media</a></li>       
        </ol> 
        {%endblock content%}

prova_pratica_0/templates/media.html
{%extends "base.html"%}
    {%block content%}
        <h1>Media</h1>
        {%for i in lista%}
            {{i}}
        {% endfor %}
        {% if media < 6 %}
            <b><p><font color="red">{{media}}</font></p>    </b> </br>
        {% elif media > 6%}
            <b><p><font color="green">{{media}}</font></p>  </b> </br>
        {%elif media == 6%}
            <b><p>{{media}}</p></b>    
        {% endif %}
    {%endblock content%}

prova_pratica_0/templates/somma.html
{%extends "base.html"%}
    {%block content%}
    {% if var1 < var2%}
        <b><p><font color="red">Variabile 1 e il numero minore {{var2}}</font></p>    </b> </br>
        <b><p><font color="green">Variabile 2 il numero maggiore {{var1}}</font></p>  </b> </br>
        <b><p>somma={{somma}}</p></b> </br>

    {%elif var1 > var2 %}
        <b><p><font color="red">Variabile 2 e il numero minore {{var2}}</font></p></b> </br>
        <b><p><font color="green">Variabile 1 il numero maggiore {{var1}}</font></p></b> <br>
        <b><p>somma={{somma}}</p></b> </br>
    {%else%}
     <b><p>I numeri son uguali: {{var1}}</p></b> </br>
     <b><p>somma={{somma}}</p></b>  </br>
     
    {%endif%} 
    {%endblock content%}

prova_pratica_2/templates/index_prova_2.html
{%extends "base.html"%}
    {%block content%}
         <ol>
            <li><a href="{% url 'prova_pratica_2:view_a'%}">Materie</a></li> 
            <li><a href="{% url 'prova_pratica_2:view_b'%}">Studenti</a></li>
            <li><a href="{% url 'prova_pratica_2:view_c'%}">Media</a></li>       
        </ol> 
    {%endblock content%}

prova_pratica_2/templates/views_a.html
{%extends "base.html"%}
{%block content%}
 <h1>Materie</h1>
<ul>
{%for i in materie%}
 <li>{{i}}</li>
{% endfor %}
</ul>
{%endblock content%}

prova_pratica_2/templates/views_b.html
{%extends "base.html"%}
    {%block content%}
        <h1>Studenti</h1>
        {% for key, values in voti.items %}
         <ul>
          <li>{{key}}</li>
           <ul>
            {% for v in values%}
             <li>{{v}}</li>
            {% endfor %}
           </ul>
         </ul> 
        {% endfor %}
    {%endblock content%}

prova_pratica_2/templates/views_c.html
{%extends "base.html"%}
    {%block content%}
        <h1>Studenti</h1>
        {% for key, values in medie.items %}   
         <ul> 
            <li>{{key}} : {{values}}</li>
         </ul>
        {% endfor %} 
    {%endblock content%}

seconda_app/templates/else_if_elif.html
{%extends "base.html"%}
        {%block content%}
        <b>var1={{var1}}</b> <br/>
        <b>var2={{var2}}</b> <br/>
        <b>var3={{var3}}</b> <br/>
        {% if var1 < var2%}
         <p><i>var1 è minore di var2</i></p>
        {%elif var1 > var2 %}
         <p><i>var1 è maggiore di var2</i></p>
        {%else%}
         <p><i>var1 è uguale a var2</i></p>
        {%endif%}
        {% if var1 > var2%}
         <p><i>var1 è maggiore di var2</i></p>
        {%elif var1 < var2 %}
         <p><i>var1 è minore di var2</i></p>
        {%else%}
         <p><i>var1 è uguale a var2</i></p>
        {%endif%}
        {% if var1 <= var2%}
         <p><i>var1 è minore o uguale di var2</i></p>
        {%elif var1 > var2 %}
         <p><i>var1 è maggiore di var2</i></p>
        {%endif%}
        {% if var1 >= var2%}
         <p><i>var1 è maggiore o uguale di var2</i></p>
        {%elif var1 < var2 %}
         <p><i>var1 è di var2</i></p>
        {%endif%}
        {% if var1 == var2%}
         <p><i>var1 è uguale a var2</i></p>
        {%elif var1 != var2 %}
         <p><i>var1 è diveso rispetto var2</i></p>
        {%endif%}
        {% if var1 < var2 or var3 < var2%}
         <p><i>var1 è minore di var2 e var1 è minore di var3</i></p>
        {% elif var1 < var2 or var3 < var2%}
         <p><i>var1 è maggiore di var2 e var1 è maggiore di var3</i></p>
        {%endif%}
        {% comment "" %}{%if not var1 > var2%}
         <p><i>var1 non è maggiore di var2</i></p>
        {%elif not var1< var2 %}
         <p><i>var1 non è minore di var2</i></p>
        {%endif%}   
        {% endcomment %}
        {% if not var1 > var2%}
         <p><i>var1 non è maggiore di var2</i></p>
        {%endif%}
 {%endblock content%}
    

seconda_app/templates/es_for.html
{%extends "base.html"%}
  {%block content%}
    Cicla una sequenza usando <b>forloop.counter</b>
 <br/>
 {%for x in list2%}
  <i>{{forloop.counter}}</i> :{{x}} <br/>
 {%endfor%}
 <br/>
 Cicla una sequenza usando <b>forloop.counter0</b>
 <br/>
 {% for x in list2 %} 
  <i>{{forloop.counter0}}</i> :{{x}} <br/>
 {%endfor%}
 <br/>
 Stampa il primo elemento della sequenza usando <b>forloop.first</b>:   
 <br/>
 {% for x in list2 %} 
  {% if forloop.first %}
   <i>Il primo elemento</i> -{{x}}
  {%endif%}
 {%endfor%}
 <br/>
 Stampa l'ultimo elemento della lista usando <b>forloop.last</b>:
 {%for x in list2%} 
  {%if forloop.last%}
   <i>L'ultimo elemento</i> -{{x}}
  {%endif%}
 {%endfor%}
 <br/>
 Stampa il numero di elementi non ancora ciclato usando <b>forloop.revcounter</b>
 <br/>
 {%for x in list2%}
  <i>Numero di elementi che deve ancora ciclare </i>-{{forloop.revcounter} <br/>
  <i>Elemento</i>-{{x}} <br/>
 {%endfor%}
 <br/>
 Stampa il numero di elementi non ancora ciclato usando <b>forloop.revcounter0</b>
 <br/>
 {%for x in list2%}
  <i>Numero di elementi che deve ancora ciclare </i>-{{forloop.revcounter0} <br/>
  <i>Elemento</i>-{{x}} <br/>
 {%endfor%}
 <br/>
 Stampa la sequenza al contrario usando <b>reversed</b>, attributo del tag <b>for</b>
 <br/>
 {%for x in list2 reversed%}
  <i>Elemento</i>-{{x}} <br/>
 {%endfor%} 
 {%endblock content%}

seconda_app/templates/es_if.html
{%extends "base.html"%}  
       {%block content%}
        <b>var1={{var1}}</b> <br/>
    <b>var2={{var2}}</b> <br/>
    <b>var3={{var3}}</b> <br/>
    {% if var1 < var2%}
     <p><i>var1 è minore di var2</i></p>
    {%endif%}
    {% if var1 > var2%}
     <p><i>var1 è maggiore di var2</i></p>
    {%endif%}
    {% if var1 <= var2%}
    <p><i>var1 è minore o uguale di var2</i></p>
    {%endif%}
    {% if var1 >= var2%}
    <p><i>var1 è maggiore o uguale di var2</i></p>
    {%endif%}
    {% if var1 == var2%}
    <p><i>var1 è uguale da var2</i></p>
    {%endif%}
    {% if var1 != var2%}
    <p><i>var1 è diverso da var2</i></p>
    {%endif%}
    {% if var1 < var2 and var1 < var2%}
    <p><i>var1 è minore o uguale di var2 e var 1 è minore di var3</i></p>
    {%endif%}
    {% if var1 < var2 or var3 < var2%}
     <p><i>var1 è minore di var2 o var3 è minore di var2</i></p>
    {%endif%}
    {% if not var1 > var2%}
    <p><i>var1 non è maggiore di var2</i></p>
    {%endif%}
{%endblock content%}

seconda_app/templates/index_seconda_app.html
{%extends 'base.html'%}
     {%block content%}
        <ol>
            <li><a href="{% url 'seconda_app:es_if'%}">es_if</a></li> 
            <li><a href="{% url 'seconda_app:else_if_elif'%}">Else_if_Elif</a></li>
            <li><a href="{% url 'seconda_app:es_for'%}">Es_for</a></li>
        </ol>
{%endblock content%}

templates/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <title>{% block title %} Primo progetto {% endblock title %}</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <style>
      body{
        background-color: rgb(231, 222, 222)
      }
      </style>
</head>
<body>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/"><i class="bi bi-house"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
      <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z"/>
    </svg></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Prima_App
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <ol>
              <li><a href="{% url 'prima_app:homepage'%}">Home page</a></li> 
              <li><a href="{% url 'prima_app:welcome'%}">Welcome</a></li>
              <li><a href="{% url 'prima_app:lista'%}">Lista</a></li>
              <li><a href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a></li>
              <li><a href="{% url 'prima_app:variabili'%}">Variabili</a></li>        
          </ol> 
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Seconda_App
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <ol>
              <li><a href="{% url 'seconda_app:es_if'%}">Es_if</a></li> 
              <li><a href="{% url 'seconda_app:else_if_elif'%}">Else_if_Elif</a></li>
              <li><a href="{% url 'seconda_app:es_for'%}">Es_for</a></li>
          </ol>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Prova_pratica_0
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <ol>
              <li><a href="{% url 'prova_pratica_0:somma'%}">Somma</a></li> 
              <li><a href="{% url 'prova_pratica_0:media'%}">Media</a></li>
          </ol>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Prova_pratica_2
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <ol>
              <li><a href="{% url 'prova_pratica_2:view_a'%}">Materie</a></li> 
              <li><a href="{% url 'prova_pratica_2:view_b'%}">Studenti</a></li>
              <li><a href="{% url 'prova_pratica_2:view_c'%}">Media</a></li>
          </ol>
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
 <div class="container my-4">
    <!--Servirà per inserire i contenuti della pagina-->
    {%block content%}
    {%endblock content%}
    <!--Servirà per inserire il contenuto javascript-->
    {%block script%}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {%endblock script%}
 </div>

</body>
</html>

templates/index_generale.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index_generale</title>
</head>
<body>
    <ol>
        <li><a href="/admin">Admin</a></li>
        <li><a href="{% url 'prima_app:index'%}">Prima_App</a></li>
        <li><a href="{% url 'seconda_app:index'%}">Seconda_App</a></li>
    </ol>
</body>
</html>